//! Hidden `hw generate-docs`: man pages (`man/`), completion scripts (`completions/`) and
//! one markdown reference (`reference/hw.md`), all derived from the clap command tree.
//! A dev tool, so it writes files directly instead of through an injected I/O seam.

use std::fmt::Write as _;
use std::fs::File;

use camino::Utf8Path;
use clap::{Command, CommandFactory};
use clap_complete::Shell;

use super::Outcome;
use crate::cli::args::{Cli, GenerateDocsArgs};

/// Runs `hw generate-docs --output-dir DIR`.
pub fn run(args: &GenerateDocsArgs) -> anyhow::Result<Outcome> {
    let out = &args.output_dir;
    let man_dir = out.join("man");
    let completions_dir = out.join("completions");
    let reference_dir = out.join("reference");
    for dir in [&man_dir, &completions_dir, &reference_dir] {
        std::fs::create_dir_all(dir)?;
    }

    let mut cmd = Cli::command();
    cmd.build();
    write_man_pages(&cmd, &[], &man_dir)?;
    write_completions(&mut cmd, &completions_dir)?;

    let mut markdown = String::from(
        "# hw command reference\n\nGenerated by `hw generate-docs` from the clap command tree; do not edit by hand.\n\n",
    );
    render_markdown(&cmd, &[], 2, &mut markdown);
    std::fs::write(reference_dir.join("hw.md"), markdown)?;

    Ok(Outcome::text(format!("Generated docs in {out}")))
}

/// Hidden commands and clap's synthetic `help` stay out of the generated docs.
fn should_skip(cmd: &Command) -> bool {
    cmd.is_hide_set() || cmd.get_name() == "help"
}

fn write_man_pages(cmd: &Command, ancestors: &[&str], out_dir: &Utf8Path) -> anyhow::Result<()> {
    if should_skip(cmd) {
        return Ok(());
    }
    let mut parts = ancestors.to_vec();
    parts.push(cmd.get_name());
    let mut file = File::create(out_dir.join(format!("{}.1", parts.join("-"))))?;
    clap_mangen::Man::new(cmd.clone()).render(&mut file)?;
    for sub in cmd.get_subcommands() {
        write_man_pages(sub, &parts, out_dir)?;
    }
    Ok(())
}

fn write_completions(cmd: &mut Command, out_dir: &Utf8Path) -> anyhow::Result<()> {
    let targets = [
        (Shell::Bash, "hw.bash"),
        (Shell::Zsh, "_hw"),
        (Shell::Fish, "hw.fish"),
        (Shell::PowerShell, "_hw.ps1"),
        (Shell::Elvish, "hw.elv"),
    ];
    for (shell, file_name) in targets {
        let mut file = File::create(out_dir.join(file_name))?;
        clap_complete::generate(shell, cmd, "hw", &mut file);
    }
    Ok(())
}

fn render_markdown(cmd: &Command, ancestors: &[&str], level: usize, out: &mut String) {
    if should_skip(cmd) {
        return;
    }
    let mut parts = ancestors.to_vec();
    parts.push(cmd.get_name());
    let full_name = parts.join(" ");

    let _ = writeln!(out, "{} {full_name}\n", "#".repeat(level.min(6)));
    if let Some(about) = cmd.get_long_about().or_else(|| cmd.get_about()) {
        let _ = writeln!(out, "{about}\n");
    }

    let usage = cmd.clone().render_usage().to_string();
    if !usage.trim().is_empty() {
        let _ = writeln!(out, "**Usage**\n\n```text\n{}\n```\n", usage.trim_end());
    }

    let args: Vec<_> = cmd
        .get_arguments()
        .filter(|a| !matches!(a.get_id().as_str(), "help" | "version") && !a.is_hide_set())
        // Global flags are documented once, on the root command.
        .filter(|a| ancestors.is_empty() || !a.is_global_set())
        .collect();
    if !args.is_empty() {
        out.push_str("**Options**\n\n");
        for arg in args {
            let name = match (arg.get_long(), arg.get_short()) {
                (Some(long), Some(short)) => format!("--{long}, -{short}"),
                (Some(long), None) => format!("--{long}"),
                (None, Some(short)) => format!("-{short}"),
                (None, None) => {
                    let value = arg
                        .get_value_names()
                        .and_then(|names| names.first().map(ToString::to_string))
                        .unwrap_or_else(|| arg.get_id().as_str().to_ascii_uppercase());
                    format!("<{value}>")
                }
            };
            match arg.get_help().or_else(|| arg.get_long_help()) {
                Some(help) => {
                    let _ = writeln!(out, "- `{name}` — {help}");
                }
                None => {
                    let _ = writeln!(out, "- `{name}`");
                }
            }
        }
        out.push('\n');
    }

    let subs: Vec<&Command> = cmd.get_subcommands().filter(|s| !should_skip(s)).collect();
    if !subs.is_empty() {
        out.push_str("**Subcommands**\n\n");
        for sub in &subs {
            match sub.get_about() {
                Some(about) => {
                    let _ = writeln!(out, "- `{}` — {about}", sub.get_name());
                }
                None => {
                    let _ = writeln!(out, "- `{}`", sub.get_name());
                }
            }
        }
        out.push('\n');
        for sub in subs {
            render_markdown(sub, &parts, level + 1, out);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use camino::Utf8PathBuf;

    #[test]
    fn writes_man_completions_and_reference_without_hidden_commands() {
        let dir = tempfile::tempdir().unwrap();
        let output_dir = Utf8PathBuf::from_path_buf(dir.path().to_path_buf()).unwrap();
        run(&GenerateDocsArgs {
            output_dir: output_dir.clone(),
        })
        .unwrap();

        for file in [
            "man/hw.1",
            "man/hw-booking-list.1",
            "completions/_hw",
            "completions/hw.bash",
        ] {
            assert!(output_dir.join(file).is_file(), "{file} missing");
        }
        assert!(!output_dir.join("man/hw-generate-docs.1").exists());
        let reference = std::fs::read_to_string(output_dir.join("reference/hw.md")).unwrap();
        assert!(reference.starts_with("# hw command reference"));
        assert!(reference.contains("## hw\n") && reference.contains("hw booking list"));
        assert!(
            !reference.contains("# hw generate-docs") && !reference.contains("`generate-docs`")
        );
    }
}
